### ISSUE TITLE
Activity 1 -> Main Page + Header + footer (wireframe 1)

### ISSUE THREAD

**Issue by ElisaMarchete** [ElisaMarchete/ShelterSeek#22]
•	Create the main page layout.
•	Design and implement the clickable card layout for shelters, including images and basic information.
•	Fetch and display the list of shelters from a database.
•	*Implement basic filtering and sorting functionality for the shelters.

**Comment by NadeemTalaat** [comment]
- [x] Header
- [x] Navigation Bar
- [ ] Main Page Content
- [x] Footer
