### ISSUE TITLE
Activity 4 -> Login, signup, and logout features - shelter view (wireframe 4, 5, and 6)

### ISSUE THREAD

**Issue by ElisaMarchete** [ElisaMarchete/ShelterSeek#26]
•	Create the login and signup page layouts. *Done*
•	Set up user registration, login, and logout functionality.
•	Handle authentication errors and provide appropriate feedback to users.
•	Implement functionality for shelters to manage their information, update details, and upload images

**Comment by peterjunpark** [comment]
- [x] Account menu
- [x] Login form
- [x] User signup form
- [x] Shelter signup form
- [x] Implement mutations for user creation, updating, deleting, auth
- [x] Implement mutations for shelter creation, updating, deleting
- [ ] Implement validation and error handling
